// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "pp1_ui.h"

Fl_Double_Window *assgn1_ui=(Fl_Double_Window *)0;

Fl_Button *ExitButton=(Fl_Button *)0;

Fl_Button *All=(Fl_Button *)0;

MainCanvas *canvas=(MainCanvas *)0;

CameraPositionCanvas *canvas2=(CameraPositionCanvas *)0;

Fl_Value_Slider *MSlider=(Fl_Value_Slider *)0;

Fl_Value_Slider *DSlider=(Fl_Value_Slider *)0;

Fl_Double_Window* create_the_forms() {
  { assgn1_ui = new Fl_Double_Window(870, 800, "assgn1_ui");
    assgn1_ui->box(FL_NO_BOX);
    { Fl_Box* o = new Fl_Box(0, 0, 870, 800);
      o->box(FL_UP_BOX);
      o->labelcolor((Fl_Color)FL_BLACK);
    } // Fl_Box* o
    { ExitButton = new Fl_Button(770, 770, 80, 20, "Exit");
      ExitButton->box(FL_SHADOW_BOX);
      ExitButton->labelfont(1);
      ExitButton->callback((Fl_Callback*)QuitProgram, (void*)(0));
    } // Fl_Button* ExitButton
    { All = new Fl_Button(0, 0, 0, 0);
      All->box(FL_NO_BOX);
      All->color((Fl_Color)1027423549);
      All->selection_color((Fl_Color)1027423549);
      All->labelcolor((Fl_Color)FL_BLACK);
    } // Fl_Button* All
    { Fl_Button* o = new Fl_Button(0, 0, 0, 0);
      o->box(FL_NO_BOX);
      o->color((Fl_Color)1651472442);
      o->selection_color((Fl_Color)1651472442);
      o->labelcolor((Fl_Color)FL_BLACK);
    } // Fl_Button* o
    { canvas = new MainCanvas(20, 20, 830, 520);
      canvas->box(FL_DOWN_BOX);
      canvas->color((Fl_Color)FL_BACKGROUND_COLOR);
      canvas->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      canvas->labeltype(FL_NORMAL_LABEL);
      canvas->labelfont(0);
      canvas->labelsize(14);
      canvas->labelcolor((Fl_Color)FL_BLACK);
      canvas->user_data((void*)(0));
      canvas->align(FL_ALIGN_CENTER);
      canvas->when(FL_WHEN_RELEASE);
    } // MainCanvas* canvas
    { canvas2 = new CameraPositionCanvas(20, 560, 360, 220);
      canvas2->box(FL_DOWN_BOX);
      canvas2->color((Fl_Color)FL_BACKGROUND_COLOR);
      canvas2->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      canvas2->labeltype(FL_NORMAL_LABEL);
      canvas2->labelfont(0);
      canvas2->labelsize(14);
      canvas2->labelcolor((Fl_Color)FL_BLACK);
      canvas2->user_data((void*)(0));
      canvas2->align(FL_ALIGN_CENTER);
      canvas2->when(FL_WHEN_RELEASE);
    } // CameraPositionCanvas* canvas2
    { MSlider = new Fl_Value_Slider(390, 560, 30, 220, "m");
      MSlider->callback((Fl_Callback*)mCallback, (void*)(0));
    } // Fl_Value_Slider* MSlider
    { DSlider = new Fl_Value_Slider(420, 560, 30, 220, "d");
      DSlider->callback((Fl_Callback*)dCallback, (void*)(0));
    } // Fl_Value_Slider* DSlider
    assgn1_ui->end();
  } // Fl_Double_Window* assgn1_ui
  return assgn1_ui;
}
